services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=resource-server-db'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    ports:
      - '25432:5432'
