services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=resource-server-db'
      - 'POSTGRES_PASSWORD=bimatnha'
      - 'POSTGRES_USER=phatdo'
    ports:
      - '25432:5432'
