spring:
  application:
    name: resource-server
  datasource:
    url: jdbc:postgresql://localhost:25432/resource-server-db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: ${JWK_SET_URI}
  profiles:
    include:
      - keystore
      - oauth2
      - s3
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 9090