spring:
  application:
    name: resource-server
  datasource:
    url: jdbc:postgresql://localhost:25432/resource-server-db
    username: phatdo
    password: bimatnha
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://127.0.0.1:9000/oauth2/jwks
  profiles:
    include:
      - keystore
      - oauth2
      - s3
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 9090